-- V001 foundation: schemas and Phase 1 registries.
-- Rendered by infrastructure/deploy_snowflake.py (the database placeholder is substituted).
-- Applied once; never edit after it has been applied to an environment - add a new V### instead.

CREATE SCHEMA IF NOT EXISTS {{database}}.SOURCE    COMMENT = 'Source registry, access checks, discovered objects, landing registry';
CREATE SCHEMA IF NOT EXISTS {{database}}.PROFILE   COMMENT = 'Column profiles';
CREATE SCHEMA IF NOT EXISTS {{database}}.KNOWLEDGE COMMENT = 'Domains, domain knowledge, target models, skills';
CREATE SCHEMA IF NOT EXISTS {{database}}.MAPPING   COMMENT = 'Embeddings, scoring config, mapping candidates and decisions';
CREATE SCHEMA IF NOT EXISTS {{database}}.CONTRACT  COMMENT = 'STTM and Soda expectation registries';
CREATE SCHEMA IF NOT EXISTS {{database}}.CODEGEN   COMMENT = 'dbt generations, generated artifacts, validation runs';
CREATE SCHEMA IF NOT EXISTS {{database}}.AUDIT     COMMENT = 'Agent runs, tool calls, cost usage';

CREATE STAGE IF NOT EXISTS {{database}}.CORE.CODE_STAGE
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Versioned Python packages imported by platform stored procedures';

-- ---------------------------------------------------------------- CORE: workflow

CREATE TABLE IF NOT EXISTS {{database}}.CORE.WORKFLOW_STATE (
    STATE          VARCHAR(64)  NOT NULL,
    STAGE          VARCHAR(32),
    KIND           VARCHAR(16)  NOT NULL,
    ORDINAL        NUMBER(6,0)  NOT NULL,
    PHASE          NUMBER(2,0)  NOT NULL,
    ENABLED        BOOLEAN      NOT NULL,
    RETRY_TO       VARCHAR(64)  NOT NULL,
    GRAPH_VERSION  VARCHAR(32)  NOT NULL,
    UPDATED_AT     TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_WORKFLOW_STATE PRIMARY KEY (STATE)
);

CREATE TABLE IF NOT EXISTS {{database}}.CORE.WORKFLOW_TRANSITION (
    FROM_STATE     VARCHAR(64)  NOT NULL,
    TO_STATE       VARCHAR(64)  NOT NULL,
    ACTOR          VARCHAR(16)  NOT NULL,   -- SYSTEM | HUMAN | ANY
    GUARD          VARCHAR(64),
    ENABLED        BOOLEAN      NOT NULL,
    GRAPH_VERSION  VARCHAR(32)  NOT NULL,
    UPDATED_AT     TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_WORKFLOW_TRANSITION PRIMARY KEY (FROM_STATE, TO_STATE)
);

CREATE TABLE IF NOT EXISTS {{database}}.CORE.WORKFLOW_RUN (
    RUN_ID             VARCHAR(36)  NOT NULL,
    RUN_NAME           VARCHAR(256) NOT NULL,
    DOMAIN_ID          VARCHAR(36),
    SOURCE_SYSTEM_ID   VARCHAR(36),
    SOURCE_DATABASE    VARCHAR(256),
    SOURCE_SCHEMA      VARCHAR(256),
    SOURCE_TABLE       VARCHAR(256),            -- summary only; selected tables live in SOURCE.SOURCE_OBJECT
    TARGET_MODEL       VARCHAR(512),
    CURRENT_STATE      VARCHAR(64)  NOT NULL,
    CURRENT_STAGE      VARCHAR(32),
    PREVIOUS_STATE     VARCHAR(64),
    FAILED_FROM_STATE  VARCHAR(64),
    STATUS             VARCHAR(32)  NOT NULL,
    STATE_VERSION      NUMBER(10,0) NOT NULL DEFAULT 0,   -- optimistic concurrency token
    CREATED_BY         VARCHAR(256) NOT NULL,
    CREATED_AT         TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT         TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT       TIMESTAMP_LTZ,
    FAILURE_REASON     VARCHAR(4000),
    RETRY_COUNT        NUMBER(6,0)  NOT NULL DEFAULT 0,
    CORRELATION_ID     VARCHAR(128),
    ENVIRONMENT        VARCHAR(32)  NOT NULL DEFAULT 'DEV',
    CONFIG_VERSION     VARCHAR(64),
    GRAPH_VERSION      VARCHAR(32)  NOT NULL,
    CONSTRAINT PK_WORKFLOW_RUN PRIMARY KEY (RUN_ID)
);

CREATE TABLE IF NOT EXISTS {{database}}.CORE.WORKFLOW_EVENT (
    EVENT_ID       VARCHAR(36)  NOT NULL,
    RUN_ID         VARCHAR(36)  NOT NULL,
    FROM_STATE     VARCHAR(64),
    TO_STATE       VARCHAR(64)  NOT NULL,
    ACTOR_TYPE     VARCHAR(16)  NOT NULL,       -- SYSTEM | HUMAN
    ACTOR          VARCHAR(256) NOT NULL,       -- Snowflake user that executed the call
    REASON         VARCHAR(4000),
    DETAILS        VARIANT,
    GRAPH_VERSION  VARCHAR(32)  NOT NULL,
    CREATED_AT     TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_WORKFLOW_EVENT PRIMARY KEY (EVENT_ID),
    CONSTRAINT FK_WORKFLOW_EVENT_RUN FOREIGN KEY (RUN_ID) REFERENCES {{database}}.CORE.WORKFLOW_RUN (RUN_ID)
);

CREATE TABLE IF NOT EXISTS {{database}}.CORE.REVIEW_DECISION (
    REVIEW_ID               VARCHAR(36)  NOT NULL,
    RUN_ID                  VARCHAR(36)  NOT NULL,
    EVENT_ID                VARCHAR(36)  NOT NULL,
    STAGE                   VARCHAR(32)  NOT NULL,
    FROM_STATE              VARCHAR(64)  NOT NULL,
    TO_STATE                VARCHAR(64)  NOT NULL,
    DECISION                VARCHAR(32)  NOT NULL,   -- APPROVE | REJECT | REQUEST_CHANGES | REOPEN
    ARTIFACT_ID             VARCHAR(36),             -- STTM_ID / GENERATION_ID / ... when applicable
    ARTIFACT_VERSION        NUMBER(6,0),
    BUSINESS_JUSTIFICATION  VARCHAR(4000),
    COMMENTS                VARCHAR(4000),
    REVIEWER                VARCHAR(256) NOT NULL,
    REVIEWED_AT             TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_REVIEW_DECISION PRIMARY KEY (REVIEW_ID),
    CONSTRAINT FK_REVIEW_DECISION_RUN FOREIGN KEY (RUN_ID) REFERENCES {{database}}.CORE.WORKFLOW_RUN (RUN_ID)
);

-- ---------------------------------------------------------------- SOURCE

CREATE TABLE IF NOT EXISTS {{database}}.SOURCE.SOURCE_REGISTRY (
    SOURCE_SYSTEM_ID         VARCHAR(36)  NOT NULL,
    SOURCE_SYSTEM_NAME       VARCHAR(256) NOT NULL,
    SOURCE_TYPE              VARCHAR(32)  NOT NULL,   -- SNOWFLAKE_SHARE | SNOWFLAKE_DATABASE | DATABASE | FILE | API | SAAS | STREAMING
    DOMAIN_ID                VARCHAR(36),
    OWNER                    VARCHAR(256),
    CONNECTION_TYPE          VARCHAR(64),
    SECURITY_CLASSIFICATION  VARCHAR(32),
    PII_FLAG                 BOOLEAN DEFAULT FALSE,
    ACTIVE_FLAG              BOOLEAN DEFAULT TRUE,
    CONFIGURATION_REFERENCE  VARCHAR(512),            -- name of a Snowflake object (mounted database, secret, integration); never a credential
    CONFIGURATION_JSON       VARIANT,                 -- non-secret adapter settings (database, schema, share name)
    CREATED_BY               VARCHAR(256) NOT NULL,
    CREATED_AT               TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT               TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_SOURCE_REGISTRY PRIMARY KEY (SOURCE_SYSTEM_ID)
);

CREATE TABLE IF NOT EXISTS {{database}}.SOURCE.SOURCE_ACCESS_CHECK (
    CHECK_ID          VARCHAR(36)  NOT NULL,
    RUN_ID            VARCHAR(36)  NOT NULL,
    SOURCE_SYSTEM_ID  VARCHAR(36)  NOT NULL,
    CHECK_NAME        VARCHAR(64)  NOT NULL,   -- CONNECTION | SHARE | DATABASE | SCHEMA | TABLES | SELECTED_OBJECTS
    STATUS            VARCHAR(16)  NOT NULL,   -- PASSED | FAILED | WARNING
    DETAIL            VARCHAR(4000),
    QUERY_ID          VARCHAR(64),
    REMEDIATION       VARCHAR(4000),
    CHECKED_AT        TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_SOURCE_ACCESS_CHECK PRIMARY KEY (CHECK_ID)
);

CREATE TABLE IF NOT EXISTS {{database}}.SOURCE.SOURCE_OBJECT (
    SOURCE_OBJECT_ID    VARCHAR(36)  NOT NULL,
    RUN_ID              VARCHAR(36)  NOT NULL,
    SOURCE_SYSTEM_ID    VARCHAR(36)  NOT NULL,
    SOURCE_DATABASE     VARCHAR(256) NOT NULL,
    SOURCE_SCHEMA       VARCHAR(256) NOT NULL,
    OBJECT_NAME         VARCHAR(256) NOT NULL,
    OBJECT_TYPE         VARCHAR(32)  NOT NULL,   -- TABLE | VIEW | ...
    ROW_COUNT_ESTIMATE  NUMBER(38,0),
    BYTES               NUMBER(38,0),
    LAST_ALTERED        TIMESTAMP_LTZ,
    SELECTED_FLAG       BOOLEAN DEFAULT FALSE,
    DISCOVERED_AT       TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_SOURCE_OBJECT PRIMARY KEY (SOURCE_OBJECT_ID)
);

CREATE TABLE IF NOT EXISTS {{database}}.SOURCE.LANDING_TABLE_REGISTRY (
    LANDING_ID            VARCHAR(36)  NOT NULL,
    RUN_ID                VARCHAR(36)  NOT NULL,
    SOURCE_SYSTEM_ID      VARCHAR(36)  NOT NULL,
    SOURCE_DATABASE       VARCHAR(256) NOT NULL,
    SOURCE_SCHEMA         VARCHAR(256) NOT NULL,
    SOURCE_TABLE          VARCHAR(256) NOT NULL,
    LANDING_DATABASE      VARCHAR(256) NOT NULL,
    LANDING_SCHEMA        VARCHAR(256) NOT NULL,
    LANDING_TABLE         VARCHAR(256) NOT NULL,
    INGESTION_METHOD      VARCHAR(32)  NOT NULL,   -- CTAS | INSERT_SELECT | COPY
    INGESTION_STATUS      VARCHAR(16)  NOT NULL,   -- PENDING | RUNNING | COMPLETE | FAILED
    ROW_COUNT             NUMBER(38,0),
    SOURCE_ROW_COUNT      NUMBER(38,0),
    SOURCE_LAST_MODIFIED  TIMESTAMP_LTZ,
    INGESTED_AT           TIMESTAMP_LTZ,
    QUERY_ID              VARCHAR(64),
    CREATED_BY            VARCHAR(256) NOT NULL,
    CREATED_AT            TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    ERROR_MESSAGE         VARCHAR(4000),
    CONSTRAINT PK_LANDING_TABLE_REGISTRY PRIMARY KEY (LANDING_ID)
);

CREATE TABLE IF NOT EXISTS {{database}}.SOURCE.LANDING_COLUMN_REGISTRY (
    LANDING_COLUMN_ID  VARCHAR(36)  NOT NULL,
    LANDING_ID         VARCHAR(36)  NOT NULL,
    COLUMN_NAME        VARCHAR(256) NOT NULL,
    DATA_TYPE          VARCHAR(256) NOT NULL,
    ORDINAL_POSITION   NUMBER(6,0)  NOT NULL,
    NULLABLE           BOOLEAN,
    SOURCE_COMMENT     VARCHAR(4000),
    MASKING_REQUIRED   BOOLEAN DEFAULT FALSE,
    CREATED_AT         TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_LANDING_COLUMN_REGISTRY PRIMARY KEY (LANDING_COLUMN_ID),
    CONSTRAINT FK_LANDING_COLUMN_TABLE FOREIGN KEY (LANDING_ID) REFERENCES {{database}}.SOURCE.LANDING_TABLE_REGISTRY (LANDING_ID)
);

-- ---------------------------------------------------------------- PROFILE

CREATE TABLE IF NOT EXISTS {{database}}.PROFILE.PROFILE_REGISTRY (
    PROFILE_ID                  VARCHAR(36)  NOT NULL,
    RUN_ID                      VARCHAR(36)  NOT NULL,
    SOURCE_TABLE_ID             VARCHAR(36)  NOT NULL,   -- LANDING_TABLE_REGISTRY.LANDING_ID
    SOURCE_COLUMN_ID            VARCHAR(36)  NOT NULL,   -- LANDING_COLUMN_REGISTRY.LANDING_COLUMN_ID
    TABLE_NAME                  VARCHAR(256) NOT NULL,
    COLUMN_NAME                 VARCHAR(256) NOT NULL,
    DATA_TYPE                   VARCHAR(256),
    PROFILE_VERSION             NUMBER(6,0)  NOT NULL,
    IS_CURRENT                  BOOLEAN      NOT NULL DEFAULT TRUE,
    ROW_COUNT                   NUMBER(38,0),
    NULL_COUNT                  NUMBER(38,0),
    NULL_PERCENTAGE             FLOAT,
    DISTINCT_COUNT              NUMBER(38,0),
    DISTINCT_PERCENTAGE         FLOAT,
    CARDINALITY                 VARCHAR(16),            -- UNIQUE | HIGH | MEDIUM | LOW | CONSTANT
    MIN_VALUE                   VARCHAR(1024),
    MAX_VALUE                   VARCHAR(1024),
    PATTERN_JSON                VARIANT,
    SAMPLE_VALUES               VARIANT,                -- stored only when PII_CLASSIFICATION permits; masked otherwise
    STATISTICS_JSON             VARIANT,
    GENERATED_DESCRIPTION       VARCHAR(4000),
    SEMANTIC_TYPE               VARCHAR(64),
    POTENTIAL_KEY_FLAG          BOOLEAN DEFAULT FALSE,
    POTENTIAL_FOREIGN_KEY_FLAG  BOOLEAN DEFAULT FALSE,
    PII_CLASSIFICATION          VARCHAR(64),
    PROFILE_STATUS              VARCHAR(16)  NOT NULL,  -- COMPLETE | FAILED | PARTIAL
    MODEL_VERSION               VARCHAR(128),
    CREATED_AT                  TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_PROFILE_REGISTRY PRIMARY KEY (PROFILE_ID)
);

-- ---------------------------------------------------------------- KNOWLEDGE

CREATE TABLE IF NOT EXISTS {{database}}.KNOWLEDGE.DOMAIN_REGISTRY (
    DOMAIN_ID    VARCHAR(36)  NOT NULL,
    DOMAIN_NAME  VARCHAR(128) NOT NULL,
    DESCRIPTION  VARCHAR(4000),
    OWNER        VARCHAR(256),
    ACTIVE_FLAG  BOOLEAN DEFAULT TRUE,
    VERSION      NUMBER(6,0)  NOT NULL DEFAULT 1,
    CREATED_AT   TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT   TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DOMAIN_REGISTRY PRIMARY KEY (DOMAIN_ID)
);

CREATE TABLE IF NOT EXISTS {{database}}.KNOWLEDGE.DOMAIN_KNOWLEDGE (
    KNOWLEDGE_ID       VARCHAR(36)  NOT NULL,
    DOMAIN_ID          VARCHAR(36)  NOT NULL,
    KNOWLEDGE_TYPE     VARCHAR(32)  NOT NULL,   -- BUSINESS_RULE | MODEL_DEFINITION | NAMING_STANDARD | DBT_PATTERN | SODA_PATTERN | TRANSFORMATION_RULE | MAPPING_PATTERN | EXCEPTION | GLOSSARY | STTM_TEMPLATE | ONBOARDING_GUIDE
    TITLE              VARCHAR(512) NOT NULL,
    CONTENT            VARCHAR(16777216) NOT NULL,   -- searchable text (Cortex Search)
    CONTENT_JSON       VARIANT,                      -- structured form used by deterministic tools
    TAGS               ARRAY,
    SOURCE_REFERENCE   VARCHAR(1024),
    STATUS             VARCHAR(16)  NOT NULL,   -- DRAFT | ACTIVE | RETIRED
    VERSION            NUMBER(6,0)  NOT NULL,
    IS_CURRENT         BOOLEAN      NOT NULL DEFAULT TRUE,
    CREATED_BY         VARCHAR(256) NOT NULL,
    CREATED_AT         TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT         TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DOMAIN_KNOWLEDGE PRIMARY KEY (KNOWLEDGE_ID)
) CHANGE_TRACKING = TRUE;

CREATE TABLE IF NOT EXISTS {{database}}.KNOWLEDGE.TARGET_TABLE_REGISTRY (
    TARGET_TABLE_ID   VARCHAR(36)  NOT NULL,
    DOMAIN_ID         VARCHAR(36)  NOT NULL,
    TARGET_DATABASE   VARCHAR(256) NOT NULL,
    TARGET_SCHEMA     VARCHAR(256) NOT NULL,
    TARGET_TABLE      VARCHAR(256) NOT NULL,
    TABLE_TYPE        VARCHAR(32),             -- DIMENSION | FACT | BRIDGE | REFERENCE
    GRAIN             VARCHAR(1024),
    BUSINESS_KEYS     ARRAY,
    SCD_TYPE          VARCHAR(16),
    DESCRIPTION       VARCHAR(4000),
    VERSION           NUMBER(6,0)  NOT NULL DEFAULT 1,
    ACTIVE_FLAG       BOOLEAN DEFAULT TRUE,
    CREATED_AT        TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_TARGET_TABLE_REGISTRY PRIMARY KEY (TARGET_TABLE_ID)
);

CREATE TABLE IF NOT EXISTS {{database}}.KNOWLEDGE.TARGET_COLUMN_REGISTRY (
    TARGET_COLUMN_ID     VARCHAR(36)  NOT NULL,
    TARGET_TABLE_ID      VARCHAR(36)  NOT NULL,
    COLUMN_NAME          VARCHAR(256) NOT NULL,
    DATA_TYPE            VARCHAR(256) NOT NULL,
    ORDINAL_POSITION     NUMBER(6,0),
    NULLABLE             BOOLEAN,
    BUSINESS_DEFINITION  VARCHAR(4000),
    SEMANTIC_TYPE        VARCHAR(64),
    IS_BUSINESS_KEY      BOOLEAN DEFAULT FALSE,
    IS_PII               BOOLEAN DEFAULT FALSE,
    ACCEPTED_VALUES      ARRAY,
    VERSION              NUMBER(6,0)  NOT NULL DEFAULT 1,
    CREATED_AT           TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_TARGET_COLUMN_REGISTRY PRIMARY KEY (TARGET_COLUMN_ID),
    CONSTRAINT FK_TARGET_COLUMN_TABLE FOREIGN KEY (TARGET_TABLE_ID) REFERENCES {{database}}.KNOWLEDGE.TARGET_TABLE_REGISTRY (TARGET_TABLE_ID)
);

CREATE TABLE IF NOT EXISTS {{database}}.KNOWLEDGE.DOMAIN_RECOMMENDATION (
    RECOMMENDATION_ID  VARCHAR(36)  NOT NULL,
    RUN_ID             VARCHAR(36)  NOT NULL,
    DOMAIN_ID          VARCHAR(36)  NOT NULL,
    CONFIDENCE         FLOAT,
    EVIDENCE_JSON      VARIANT,
    MATCHED_KNOWLEDGE  VARIANT,
    RECOMMENDATION     VARCHAR(4000),
    STATUS             VARCHAR(16)  NOT NULL,   -- PROPOSED | ACCEPTED | OVERRIDDEN
    DECIDED_BY         VARCHAR(256),
    DECIDED_AT         TIMESTAMP_LTZ,
    MODEL_VERSION      VARCHAR(128),
    CREATED_AT         TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DOMAIN_RECOMMENDATION PRIMARY KEY (RECOMMENDATION_ID)
);

CREATE TABLE IF NOT EXISTS {{database}}.KNOWLEDGE.SKILL_REGISTRY (
    SKILL_ID     VARCHAR(36)  NOT NULL,
    SKILL_NAME   VARCHAR(128) NOT NULL,
    SKILL_TYPE   VARCHAR(32)  NOT NULL,   -- SOURCE_ONBOARDING | DOMAIN | MAPPING | STTM | SODA | DBT | VALIDATION
    DOMAIN_ID    VARCHAR(36),
    VERSION      VARCHAR(32)  NOT NULL,
    STAGE_PATH   VARCHAR(1024) NOT NULL,
    CHECKSUM     VARCHAR(64)  NOT NULL,
    STATUS       VARCHAR(16)  NOT NULL,   -- DRAFT | ACTIVE | RETIRED
    CREATED_BY   VARCHAR(256) NOT NULL,
    CREATED_AT   TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_SKILL_REGISTRY PRIMARY KEY (SKILL_ID)
);

-- ---------------------------------------------------------------- MAPPING

CREATE TABLE IF NOT EXISTS {{database}}.MAPPING.MAPPING_SCORING_CONFIG (
    CONFIG_ID    VARCHAR(36)  NOT NULL,
    DOMAIN_ID    VARCHAR(36),             -- NULL = platform default
    VERSION      NUMBER(6,0)  NOT NULL,
    WEIGHTS      VARIANT      NOT NULL,   -- {"semantic":..,"keyword":..,"datatype":..,"statistical":..,"domain":..,"context":..,"historical":..}
    THRESHOLDS   VARIANT      NOT NULL,   -- {"auto_suggest":..,"human_review":..}
    ACTIVE_FLAG  BOOLEAN      NOT NULL DEFAULT FALSE,
    CREATED_BY   VARCHAR(256) NOT NULL,
    CREATED_AT   TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_MAPPING_SCORING_CONFIG PRIMARY KEY (CONFIG_ID)
);

CREATE TABLE IF NOT EXISTS {{database}}.MAPPING.COLUMN_EMBEDDING (
    EMBEDDING_ID    VARCHAR(36)  NOT NULL,
    OBJECT_KIND     VARCHAR(16)  NOT NULL,   -- SOURCE_COLUMN | TARGET_COLUMN
    OBJECT_ID       VARCHAR(36)  NOT NULL,
    EMBED_MODEL     VARCHAR(128) NOT NULL,
    EMBED_TEXT      VARCHAR(4000) NOT NULL,
    EMBEDDING       VECTOR(FLOAT, 1024) NOT NULL,
    TEXT_SHA256     VARCHAR(64)  NOT NULL,
    CREATED_AT      TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_COLUMN_EMBEDDING PRIMARY KEY (EMBEDDING_ID)
);

CREATE TABLE IF NOT EXISTS {{database}}.MAPPING.MAPPING_CANDIDATE (
    CANDIDATE_ID       VARCHAR(36)  NOT NULL,
    RUN_ID             VARCHAR(36)  NOT NULL,
    SOURCE_COLUMN_ID   VARCHAR(36)  NOT NULL,
    TARGET_COLUMN_ID   VARCHAR(36)  NOT NULL,
    DOMAIN_ID          VARCHAR(36),
    SEMANTIC_SCORE     FLOAT,
    KEYWORD_SCORE      FLOAT,
    DATATYPE_SCORE     FLOAT,
    STATISTICAL_SCORE  FLOAT,
    DOMAIN_SCORE       FLOAT,
    CONTEXT_SCORE      FLOAT,
    HISTORICAL_SCORE   FLOAT,
    FINAL_SCORE        FLOAT        NOT NULL,
    RANK               NUMBER(4,0)  NOT NULL,
    CONFIDENCE         FLOAT,
    RECOMMENDATION     VARCHAR(16)  NOT NULL,   -- AUTO_SUGGEST | HUMAN_REVIEW | MANUAL
    EVIDENCE_JSON      VARIANT,
    GENERATED_REASON   VARCHAR(4000),
    TRANSFORMATION     VARCHAR(4000),
    SCORING_CONFIG_ID  VARCHAR(36)  NOT NULL,
    MODEL_VERSION      VARCHAR(128),
    KNOWLEDGE_VERSION  VARCHAR(64),
    CANDIDATE_VERSION  NUMBER(6,0)  NOT NULL,
    IS_CURRENT         BOOLEAN      NOT NULL DEFAULT TRUE,
    CREATED_AT         TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_MAPPING_CANDIDATE PRIMARY KEY (CANDIDATE_ID)
);

CREATE TABLE IF NOT EXISTS {{database}}.MAPPING.MAPPING_DECISION (
    DECISION_ID             VARCHAR(36)  NOT NULL,
    RUN_ID                  VARCHAR(36)  NOT NULL,
    CANDIDATE_ID            VARCHAR(36),             -- NULL when the reviewer chose a target that was not proposed
    SOURCE_COLUMN_ID        VARCHAR(36)  NOT NULL,
    TARGET_COLUMN_ID        VARCHAR(36),             -- NULL for REJECT without alternative
    DECISION                VARCHAR(32)  NOT NULL,   -- APPROVED | REJECTED | MODIFIED | ALTERNATIVE_TARGET
    TRANSFORMATION          VARCHAR(4000),
    BUSINESS_JUSTIFICATION  VARCHAR(4000),
    COMMENTS                VARCHAR(4000),
    REVIEWER                VARCHAR(256) NOT NULL,
    REVIEWED_AT             TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    VERSION                 NUMBER(6,0)  NOT NULL,
    IS_CURRENT              BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_MAPPING_DECISION PRIMARY KEY (DECISION_ID)
);

-- ---------------------------------------------------------------- CONTRACT

CREATE TABLE IF NOT EXISTS {{database}}.CONTRACT.STTM_REGISTRY (
    STTM_ID             VARCHAR(36)  NOT NULL,
    RUN_ID              VARCHAR(36)  NOT NULL,
    DOMAIN_ID           VARCHAR(36)  NOT NULL,
    TARGET_TABLE_ID     VARCHAR(36)  NOT NULL,
    STTM_VERSION        NUMBER(6,0)  NOT NULL,
    STATUS              VARCHAR(16)  NOT NULL,   -- DRAFT | REVIEW | APPROVED | REJECTED | SUPERSEDED
    TABLE_DESIGN        VARIANT,                 -- grain, business keys, join paths, dedup, SCD, incremental strategy
    KNOWLEDGE_VERSION   VARCHAR(64),
    SKILL_VERSION       VARCHAR(64),
    GENERATION_VERSION  VARCHAR(64),
    CREATED_BY          VARCHAR(256) NOT NULL,
    CREATED_AT          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    REVIEWED_BY         VARCHAR(256),
    REVIEWED_AT         TIMESTAMP_LTZ,
    CONSTRAINT PK_STTM_REGISTRY PRIMARY KEY (STTM_ID)
);

CREATE TABLE IF NOT EXISTS {{database}}.CONTRACT.STTM_LINE (
    STTM_LINE_ID         VARCHAR(36)  NOT NULL,
    STTM_ID              VARCHAR(36)  NOT NULL,
    DECISION_ID          VARCHAR(36),
    SOURCE_SYSTEM        VARCHAR(256),
    SOURCE_DATABASE      VARCHAR(256),
    SOURCE_SCHEMA        VARCHAR(256),
    SOURCE_TABLE         VARCHAR(256),
    SOURCE_COLUMN        VARCHAR(256),
    SOURCE_DATATYPE      VARCHAR(256),
    TARGET_DOMAIN        VARCHAR(128) NOT NULL,
    TARGET_DATABASE      VARCHAR(256) NOT NULL,
    TARGET_SCHEMA        VARCHAR(256) NOT NULL,
    TARGET_TABLE         VARCHAR(256) NOT NULL,
    TARGET_COLUMN        VARCHAR(256) NOT NULL,
    TARGET_DATATYPE      VARCHAR(256) NOT NULL,
    MAPPING_TYPE         VARCHAR(32)  NOT NULL,   -- DIRECT | TRANSFORM | DERIVED | LOOKUP | CONSTANT | UNMAPPED
    TRANSFORMATION       VARCHAR(4000),
    BUSINESS_RULE        VARCHAR(4000),
    BUSINESS_DEFINITION  VARCHAR(4000),
    NULLABLE_RULE        BOOLEAN,
    UNIQUENESS_RULE      BOOLEAN,
    ACCEPTED_VALUES      ARRAY,
    RANGE_RULE           VARIANT,
    SCD_BEHAVIOR         VARCHAR(32),
    DEFAULT_VALUE        VARCHAR(1024),
    FILTER_RULE          VARCHAR(4000),
    JOIN_LOGIC           VARCHAR(4000),
    LOOKUP_LOGIC         VARCHAR(4000),
    EXCEPTION_HANDLING   VARCHAR(4000),
    MAPPING_CONFIDENCE   FLOAT,
    HUMAN_APPROVED       BOOLEAN      NOT NULL DEFAULT FALSE,
    REVIEWER             VARCHAR(256),
    APPROVAL_TIMESTAMP   TIMESTAMP_LTZ,
    CREATED_AT           TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_STTM_LINE PRIMARY KEY (STTM_LINE_ID),
    CONSTRAINT FK_STTM_LINE_STTM FOREIGN KEY (STTM_ID) REFERENCES {{database}}.CONTRACT.STTM_REGISTRY (STTM_ID)
);

CREATE TABLE IF NOT EXISTS {{database}}.CONTRACT.SODA_EXPECTATION_REGISTRY (
    EXPECTATION_ID      VARCHAR(36)  NOT NULL,
    RUN_ID              VARCHAR(36)  NOT NULL,
    STTM_ID             VARCHAR(36),
    DOMAIN_ID           VARCHAR(36)  NOT NULL,
    TARGET_TABLE        VARCHAR(256) NOT NULL,
    TARGET_COLUMN       VARCHAR(256),            -- NULL for table-level checks (row count, freshness)
    CHECK_TYPE          VARCHAR(32)  NOT NULL,   -- NOT_NULL | UNIQUE | DUPLICATE | ACCEPTED_VALUES | RANGE | FRESHNESS | ROW_COUNT | REFERENTIAL_INTEGRITY | DISTRIBUTION | CUSTOM
    CHECK_DEFINITION    VARIANT      NOT NULL,
    THRESHOLD           VARIANT,
    SEVERITY            VARCHAR(16)  NOT NULL,   -- WARN | FAIL
    ORIGIN              VARCHAR(16)  NOT NULL,   -- STTM | CLIENT | DOMAIN_RULE | AI
    CLIENT_REQUIREMENT  VARCHAR(4000),
    STATUS              VARCHAR(16)  NOT NULL,   -- PROPOSED | APPROVED | REJECTED | SUPERSEDED
    VERSION             NUMBER(6,0)  NOT NULL,
    IS_CURRENT          BOOLEAN      NOT NULL DEFAULT TRUE,
    CREATED_BY          VARCHAR(256) NOT NULL,
    CREATED_AT          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    REVIEWED_BY         VARCHAR(256),
    REVIEWED_AT         TIMESTAMP_LTZ,
    CONSTRAINT PK_SODA_EXPECTATION_REGISTRY PRIMARY KEY (EXPECTATION_ID)
);

-- ---------------------------------------------------------------- CODEGEN

CREATE TABLE IF NOT EXISTS {{database}}.CODEGEN.DBT_GENERATION_REGISTRY (
    GENERATION_ID         VARCHAR(36)  NOT NULL,
    RUN_ID                VARCHAR(36)  NOT NULL,
    PARENT_GENERATION_ID  VARCHAR(36),
    DOMAIN                VARCHAR(128) NOT NULL,
    TARGET_MODEL          VARCHAR(512) NOT NULL,
    STTM_ID               VARCHAR(36)  NOT NULL,
    STTM_VERSION          NUMBER(6,0)  NOT NULL,
    FILES_GENERATED       NUMBER(6,0),
    SKILL_VERSION         VARCHAR(64),
    KNOWLEDGE_VERSION     VARCHAR(64),
    MODEL_VERSION         VARCHAR(128),
    GENERATION_VERSION    NUMBER(6,0)  NOT NULL,
    GENERATION_STATUS     VARCHAR(16)  NOT NULL,   -- GENERATING | GENERATED | FAILED | APPROVED | CHANGES_REQUESTED | SUPERSEDED
    STAGE_PATH            VARCHAR(1024),
    CREATED_BY            VARCHAR(256) NOT NULL,
    CREATED_AT            TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DBT_GENERATION_REGISTRY PRIMARY KEY (GENERATION_ID)
);

CREATE TABLE IF NOT EXISTS {{database}}.CODEGEN.GENERATED_ARTIFACT (
    ARTIFACT_ID     VARCHAR(36)  NOT NULL,
    GENERATION_ID   VARCHAR(36)  NOT NULL,
    RUN_ID          VARCHAR(36)  NOT NULL,
    ARTIFACT_TYPE   VARCHAR(32)  NOT NULL,   -- DBT_MODEL | DBT_SCHEMA_YML | DBT_SOURCES_YML | DBT_MACRO | DBT_SNAPSHOT | DBT_PROJECT | SODA_CHECKS | STTM_EXPORT
    FILE_PATH       VARCHAR(1024) NOT NULL,
    CONTENT         VARCHAR(16777216) NOT NULL,
    CONTENT_SHA256  VARCHAR(64)  NOT NULL,
    CREATED_AT      TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_GENERATED_ARTIFACT PRIMARY KEY (ARTIFACT_ID)
);

CREATE TABLE IF NOT EXISTS {{database}}.CODEGEN.VALIDATION_RUN (
    VALIDATION_ID    VARCHAR(36)  NOT NULL,
    RUN_ID           VARCHAR(36)  NOT NULL,
    GENERATION_ID    VARCHAR(36),
    VALIDATION_TYPE  VARCHAR(32)  NOT NULL,   -- DBT_PARSE | DBT_COMPILE | DBT_TEST | SQL | NAMING | SCHEMA | REQUIRED_COLUMNS | DATATYPE | STTM_CONSISTENCY | SODA_CONFIG
    STATUS           VARCHAR(16)  NOT NULL,   -- RUNNING | PASSED | FAILED | ERROR
    ERROR_COUNT      NUMBER(6,0)  DEFAULT 0,
    WARNING_COUNT    NUMBER(6,0)  DEFAULT 0,
    RESULT_JSON      VARIANT,
    QUERY_ID         VARCHAR(64),
    STARTED_AT       TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT     TIMESTAMP_LTZ,
    LOG_LOCATION     VARCHAR(1024),
    CONSTRAINT PK_VALIDATION_RUN PRIMARY KEY (VALIDATION_ID)
);

-- ---------------------------------------------------------------- AUDIT

CREATE TABLE IF NOT EXISTS {{database}}.AUDIT.AGENT_RUN (
    AGENT_RUN_ID       VARCHAR(36)  NOT NULL,
    RUN_ID             VARCHAR(36),
    THREAD_ID          VARCHAR(64),
    AGENT_NAME         VARCHAR(128) NOT NULL,
    PARENT_AGENT       VARCHAR(128),
    MODEL              VARCHAR(128),
    PROMPT_VERSION     VARCHAR(64),
    SKILL_VERSION      VARCHAR(64),
    KNOWLEDGE_VERSION  VARCHAR(64),
    STATUS             VARCHAR(16)  NOT NULL,   -- RUNNING | SUCCEEDED | FAILED | CANCELLED | TIMEOUT
    STARTED_AT         TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT       TIMESTAMP_LTZ,
    TOKENS             NUMBER(12,0),
    ERROR              VARCHAR(4000),
    RESULT_SUMMARY     VARCHAR(4000),
    INITIATED_BY       VARCHAR(256),
    CONSTRAINT PK_AGENT_RUN PRIMARY KEY (AGENT_RUN_ID)
);

CREATE TABLE IF NOT EXISTS {{database}}.AUDIT.AGENT_TOOL_CALL (
    TOOL_CALL_ID    VARCHAR(36)  NOT NULL,
    AGENT_RUN_ID    VARCHAR(36),
    RUN_ID          VARCHAR(36),
    TOOL_NAME       VARCHAR(128) NOT NULL,
    INPUT_JSON      VARIANT,                 -- redacted inputs only; never secrets or raw sample values
    OUTPUT_SUMMARY  VARCHAR(4000),
    STATUS          VARCHAR(16)  NOT NULL,   -- SUCCEEDED | FAILED | REJECTED
    DURATION_MS     NUMBER(12,0),
    QUERY_ID        VARCHAR(64),
    ERROR           VARCHAR(4000),
    CALLED_BY       VARCHAR(256),
    CREATED_AT      TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_AGENT_TOOL_CALL PRIMARY KEY (TOOL_CALL_ID)
);

CREATE TABLE IF NOT EXISTS {{database}}.AUDIT.COST_USAGE (
    COST_USAGE_ID      VARCHAR(36)  NOT NULL,
    RUN_ID             VARCHAR(36),
    AGENT_RUN_ID       VARCHAR(36),
    STAGE              VARCHAR(32),
    AGENT              VARCHAR(128),
    MODEL              VARCHAR(128),
    INPUT_TOKENS       NUMBER(12,0),
    OUTPUT_TOKENS      NUMBER(12,0),
    TOTAL_TOKENS       NUMBER(12,0),
    TOOL_CALL_COUNT    NUMBER(6,0),
    SEARCH_CALL_COUNT  NUMBER(6,0),
    CODE_CALL_COUNT    NUMBER(6,0),
    DURATION_MS        NUMBER(12,0),
    ESTIMATED_COST     NUMBER(18,6),
    CREATED_AT         TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_COST_USAGE PRIMARY KEY (COST_USAGE_ID)
);
