-- V004: platform configuration, skill content, stages for skills and generated dbt projects,
-- and the schema that generated dbt models target in development.

CREATE TABLE IF NOT EXISTS {{database}}.CORE.PLATFORM_CONFIG (
    CONFIG_KEY    VARCHAR(128) NOT NULL,
    CONFIG_VALUE  VARIANT      NOT NULL,
    DESCRIPTION   VARCHAR(1024),
    VERSION       NUMBER(6,0)  NOT NULL,
    IS_CURRENT    BOOLEAN      NOT NULL DEFAULT TRUE,
    CREATED_BY    VARCHAR(256) NOT NULL,
    CREATED_AT    TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_PLATFORM_CONFIG PRIMARY KEY (CONFIG_KEY, VERSION)
);

ALTER TABLE {{database}}.KNOWLEDGE.SKILL_REGISTRY ADD COLUMN IF NOT EXISTS DESCRIPTION VARCHAR(1024);
ALTER TABLE {{database}}.KNOWLEDGE.SKILL_REGISTRY ADD COLUMN IF NOT EXISTS CONTENT VARCHAR(16777216);
ALTER TABLE {{database}}.KNOWLEDGE.SKILL_REGISTRY ADD COLUMN IF NOT EXISTS CONFIG VARIANT;
ALTER TABLE {{database}}.KNOWLEDGE.SKILL_REGISTRY ADD COLUMN IF NOT EXISTS IS_CURRENT BOOLEAN DEFAULT TRUE;

CREATE STAGE IF NOT EXISTS {{database}}.KNOWLEDGE.SKILL_STAGE
  COMMENT = 'Versioned agent skills: <skill>/<version>/SKILL.md';

CREATE STAGE IF NOT EXISTS {{database}}.CODEGEN.DBT_STAGE
  COMMENT = 'Generated dbt projects: <run_id>/v<generation_version>/...';

CREATE SCHEMA IF NOT EXISTS {{database}}.GDP_SILVER
  COMMENT = 'Development target schema of generated GDP dbt models (compiled only in Phase 1)';

GRANT USAGE ON SCHEMA {{database}}.GDP_SILVER TO DATABASE ROLE {{database}}.VIEWER;
GRANT READ ON STAGE {{database}}.KNOWLEDGE.SKILL_STAGE TO DATABASE ROLE {{database}}.SERVICE_AGENT;
GRANT READ ON STAGE {{database}}.CODEGEN.DBT_STAGE TO DATABASE ROLE {{database}}.REVIEWER;
