-- V006 persistent table profiles and run lifecycle.
-- Profiles move out of run scope: one JSON document per source table on METADATA.PROFILES_STAGE,
-- indexed by METADATA.TABLE_PROFILES, reused by every later run of the same source.
-- Run cleanup never touches this schema.

CREATE SCHEMA IF NOT EXISTS {{database}}.METADATA
  COMMENT = 'Cross-run metadata: persistent table profiles shared by all runs';

CREATE FILE FORMAT IF NOT EXISTS {{database}}.METADATA.PROFILE_JSON_FORMAT
  TYPE = 'JSON'
  STRIP_OUTER_ARRAY = FALSE
  COMMENT = 'One table profile document per staged file';

CREATE STAGE IF NOT EXISTS {{database}}.METADATA.PROFILES_STAGE
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  DIRECTORY = (ENABLE = TRUE)
  FILE_FORMAT = (TYPE = 'JSON')
  COMMENT = 'Table profiles: <SOURCE>/<DATABASE>/<SCHEMA>/<TABLE>.json';

CREATE TABLE IF NOT EXISTS {{database}}.METADATA.TABLE_PROFILES (
    SOURCE_NAME         VARCHAR(256)  NOT NULL,
    DATABASE_NAME       VARCHAR(256)  NOT NULL,
    SCHEMA_NAME         VARCHAR(256)  NOT NULL,
    TABLE_NAME          VARCHAR(256)  NOT NULL,
    ROW_COUNT           NUMBER(38,0),
    COLUMN_COUNT        NUMBER(10,0),
    PROFILE_STAGE_PATH  VARCHAR(1024) NOT NULL,   -- relative to @METADATA.PROFILES_STAGE
    PROFILE_CHECKSUM    VARCHAR(64)   NOT NULL,   -- sha256 of the staged document
    SOURCE_FINGERPRINT  VARCHAR(64)   NOT NULL,   -- columns, row count, last altered; a mismatch means stale
    IS_APPROXIMATE      BOOLEAN       DEFAULT FALSE,
    PROFILER_VERSION    VARCHAR(16),
    MODEL_VERSION       VARCHAR(128),
    PROFILED_IN_RUN     VARCHAR(36),
    PROFILED_BY         VARCHAR(256),
    PROFILED_AT         TIMESTAMP_LTZ NOT NULL,
    CONSTRAINT PK_TABLE_PROFILES PRIMARY KEY (SOURCE_NAME, DATABASE_NAME, SCHEMA_NAME, TABLE_NAME)
);

GRANT USAGE ON SCHEMA {{database}}.METADATA TO DATABASE ROLE {{database}}.VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA {{database}}.METADATA TO DATABASE ROLE {{database}}.VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA {{database}}.METADATA TO DATABASE ROLE {{database}}.VIEWER;
GRANT READ ON STAGE {{database}}.METADATA.PROFILES_STAGE TO DATABASE ROLE {{database}}.VIEWER;
GRANT USAGE ON FILE FORMAT {{database}}.METADATA.PROFILE_JSON_FORMAT TO DATABASE ROLE {{database}}.VIEWER;

-- ---------------------------------------------------------------- run lifecycle
-- STATUS stays owned by the workflow state machine. The lifecycle shown in the UI
-- (DRAFT, RUNNING, COMPLETED, FAILED, ARCHIVED) is derived from CURRENT_STATE and IS_ARCHIVED.
-- Deletion is soft so CORE.WORKFLOW_EVENT and CORE.REVIEW_DECISION keep their audit trail.

ALTER TABLE {{database}}.CORE.WORKFLOW_RUN ADD COLUMN IF NOT EXISTS IS_ARCHIVED BOOLEAN DEFAULT FALSE;
ALTER TABLE {{database}}.CORE.WORKFLOW_RUN ADD COLUMN IF NOT EXISTS ARCHIVED_AT TIMESTAMP_LTZ;
ALTER TABLE {{database}}.CORE.WORKFLOW_RUN ADD COLUMN IF NOT EXISTS ARCHIVED_BY VARCHAR(256);
ALTER TABLE {{database}}.CORE.WORKFLOW_RUN ADD COLUMN IF NOT EXISTS DELETED_AT TIMESTAMP_LTZ;
ALTER TABLE {{database}}.CORE.WORKFLOW_RUN ADD COLUMN IF NOT EXISTS DELETED_BY VARCHAR(256);

-- Target landing definition, decoupled from source inspection. NULL means the platform default
-- (<platform database>.LANDING, managed tables).
ALTER TABLE {{database}}.CORE.WORKFLOW_RUN ADD COLUMN IF NOT EXISTS LANDING_DATABASE VARCHAR(256);
ALTER TABLE {{database}}.CORE.WORKFLOW_RUN ADD COLUMN IF NOT EXISTS LANDING_SCHEMA VARCHAR(256);
ALTER TABLE {{database}}.CORE.WORKFLOW_RUN ADD COLUMN IF NOT EXISTS STORAGE_TYPE VARCHAR(16) DEFAULT 'MANAGED';

UPDATE {{database}}.CORE.WORKFLOW_RUN SET IS_ARCHIVED = FALSE WHERE IS_ARCHIVED IS NULL;
