-- V007 profile lifecycle status and in-place source profiling.
-- Profiling now reads source tables in place (no landing copy); the profile store tracks per-table status
-- so the Sources hub can show Unprofiled / Profiling / Staged & ready / Failed across sessions.

ALTER TABLE {{database}}.METADATA.TABLE_PROFILES ADD COLUMN IF NOT EXISTS STATUS VARCHAR(32) DEFAULT 'STAGED_READY_FOR_MODELING';
ALTER TABLE {{database}}.METADATA.TABLE_PROFILES ADD COLUMN IF NOT EXISTS STATUS_UPDATED_AT TIMESTAMP_LTZ;
ALTER TABLE {{database}}.METADATA.TABLE_PROFILES ADD COLUMN IF NOT EXISTS ERROR_MESSAGE VARCHAR(4000);
ALTER TABLE {{database}}.METADATA.TABLE_PROFILES ADD COLUMN IF NOT EXISTS AVG_NULL_PERCENTAGE FLOAT;
ALTER TABLE {{database}}.METADATA.TABLE_PROFILES ADD COLUMN IF NOT EXISTS KEY_CANDIDATES NUMBER(10,0);
ALTER TABLE {{database}}.METADATA.TABLE_PROFILES ADD COLUMN IF NOT EXISTS PII_COLUMNS NUMBER(10,0);

UPDATE {{database}}.METADATA.TABLE_PROFILES
   SET STATUS = 'STAGED_READY_FOR_MODELING', STATUS_UPDATED_AT = PROFILED_AT
 WHERE STATUS IS NULL;

-- In-place profiling runs with the caller's role (it reads the source); it writes the profile store directly.
GRANT USAGE ON SCHEMA {{database}}.METADATA TO DATABASE ROLE {{database}}.DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE ON TABLE {{database}}.METADATA.TABLE_PROFILES TO DATABASE ROLE {{database}}.DATA_ENGINEER;
GRANT READ, WRITE ON STAGE {{database}}.METADATA.PROFILES_STAGE TO DATABASE ROLE {{database}}.DATA_ENGINEER;
GRANT USAGE ON FILE FORMAT {{database}}.METADATA.PROFILE_JSON_FORMAT TO DATABASE ROLE {{database}}.DATA_ENGINEER;
