-- Saved QA test queries (AI-written or edited by a tester); generated tests are derived from the STTM on demand.
CREATE TABLE IF NOT EXISTS {{database}}.CONTRACT.QA_TEST_CASE (
    TEST_ID        VARCHAR(36)   NOT NULL,
    RUN_ID         VARCHAR(36)   NOT NULL,
    STTM_ID        VARCHAR(36),
    CATEGORY       VARCHAR(32)   NOT NULL,
    TITLE          VARCHAR(500)  NOT NULL,
    OBJECTIVE      VARCHAR(4000),
    SQL_TEXT       VARCHAR(16000) NOT NULL,
    EXPECTED       VARCHAR(1000),
    SEVERITY       VARCHAR(16)   DEFAULT 'MEDIUM',
    TARGET_COLUMN  VARCHAR(256),
    ORIGIN         VARCHAR(16)   NOT NULL,   -- AI | USER
    PROMPT         VARCHAR(4000),
    IS_DELETED     BOOLEAN       DEFAULT FALSE,
    CREATED_BY     VARCHAR(256)  DEFAULT CURRENT_USER(),
    CREATED_AT     TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_QA_TEST_CASE PRIMARY KEY (TEST_ID)
);

GRANT SELECT, INSERT, UPDATE ON TABLE {{database}}.CONTRACT.QA_TEST_CASE TO DATABASE ROLE {{database}}.DATA_ENGINEER;
GRANT SELECT ON TABLE {{database}}.CONTRACT.QA_TEST_CASE TO DATABASE ROLE {{database}}.REVIEWER;
