-- User tags on profiles (DATABASE.SCHEMA.TABLE), runs (RUN_ID) and models (target DB.SCHEMA.TABLE). A side table,
-- because METADATA.TABLE_PROFILES rows are rewritten on every re-profile.
CREATE TABLE IF NOT EXISTS {{database}}.CORE.TAG (
    TAG          VARCHAR(40)   NOT NULL,
    COLOR        VARCHAR(16),
    DESCRIPTION  VARCHAR(500),
    CREATED_BY   VARCHAR(256)  DEFAULT CURRENT_USER(),
    CREATED_AT   TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_TAG PRIMARY KEY (TAG)
);

CREATE TABLE IF NOT EXISTS {{database}}.CORE.TAG_ASSIGNMENT (
    ENTITY_TYPE  VARCHAR(16)   NOT NULL,   -- PROFILE | RUN | MODEL
    ENTITY_KEY   VARCHAR(1024) NOT NULL,
    TAG          VARCHAR(40)   NOT NULL,
    CREATED_BY   VARCHAR(256)  DEFAULT CURRENT_USER(),
    CREATED_AT   TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_TAG_ASSIGNMENT PRIMARY KEY (ENTITY_TYPE, ENTITY_KEY, TAG)
);

GRANT SELECT, INSERT, UPDATE ON TABLE {{database}}.CORE.TAG TO DATABASE ROLE {{database}}.DATA_ENGINEER;
GRANT SELECT, INSERT, DELETE ON TABLE {{database}}.CORE.TAG_ASSIGNMENT TO DATABASE ROLE {{database}}.DATA_ENGINEER;
GRANT SELECT ON TABLE {{database}}.CORE.TAG TO DATABASE ROLE {{database}}.VIEWER;
GRANT SELECT ON TABLE {{database}}.CORE.TAG_ASSIGNMENT TO DATABASE ROLE {{database}}.VIEWER;
