-- Governance: app roles (Snowflake-style: privileges granted to roles, roles granted to roles and to users),
-- approval policies per action, change requests routed to approver roles, and the governance audit log.
-- System roles, default policies and the first super admin are seeded by the API on first use.
CREATE SCHEMA IF NOT EXISTS {{database}}.GOVERNANCE COMMENT = 'App roles, approval policies and change requests';

CREATE TABLE IF NOT EXISTS {{database}}.GOVERNANCE.APP_ROLE (
    ROLE_NAME    VARCHAR(64)   NOT NULL,
    DESCRIPTION  VARCHAR(500),
    IS_SYSTEM    BOOLEAN       DEFAULT FALSE,
    CREATED_BY   VARCHAR(256)  DEFAULT CURRENT_USER(),
    CREATED_AT   TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_APP_ROLE PRIMARY KEY (ROLE_NAME)
);
CREATE TABLE IF NOT EXISTS {{database}}.GOVERNANCE.ROLE_PRIVILEGE (
    ROLE_NAME  VARCHAR(64) NOT NULL,
    PRIVILEGE  VARCHAR(64) NOT NULL,
    CONSTRAINT PK_ROLE_PRIVILEGE PRIMARY KEY (ROLE_NAME, PRIVILEGE)
);
CREATE TABLE IF NOT EXISTS {{database}}.GOVERNANCE.ROLE_GRANT (
    ROLE_NAME     VARCHAR(64) NOT NULL,   -- this role ...
    GRANTED_ROLE  VARCHAR(64) NOT NULL,   -- ... inherits everything of this role
    CONSTRAINT PK_ROLE_GRANT PRIMARY KEY (ROLE_NAME, GRANTED_ROLE)
);
CREATE TABLE IF NOT EXISTS {{database}}.GOVERNANCE.USER_ROLE (
    USER_NAME   VARCHAR(256) NOT NULL,    -- Snowflake user name
    ROLE_NAME   VARCHAR(64)  NOT NULL,
    GRANTED_BY  VARCHAR(256) DEFAULT CURRENT_USER(),
    GRANTED_AT  TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_USER_ROLE PRIMARY KEY (USER_NAME, ROLE_NAME)
);
CREATE TABLE IF NOT EXISTS {{database}}.GOVERNANCE.APPROVAL_POLICY (
    PRIVILEGE          VARCHAR(64)  NOT NULL,
    REQUIRES_APPROVAL  BOOLEAN      DEFAULT TRUE,
    APPROVER_ROLE      VARCHAR(64)  NOT NULL,
    FOUR_EYES          BOOLEAN      DEFAULT FALSE,   -- even privilege holders go through approval
    ALLOW_SELF         BOOLEAN      DEFAULT FALSE,   -- the requester may approve their own request
    ACTIVE             BOOLEAN      DEFAULT TRUE,
    UPDATED_BY         VARCHAR(256) DEFAULT CURRENT_USER(),
    UPDATED_AT         TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_APPROVAL_POLICY PRIMARY KEY (PRIVILEGE)
);
CREATE TABLE IF NOT EXISTS {{database}}.GOVERNANCE.SETTING (
    SETTING_KEY  VARCHAR(64) NOT NULL,
    SETTING_VALUE VARIANT,
    UPDATED_BY   VARCHAR(256) DEFAULT CURRENT_USER(),
    UPDATED_AT   TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_GOV_SETTING PRIMARY KEY (SETTING_KEY)
);
CREATE TABLE IF NOT EXISTS {{database}}.GOVERNANCE.CHANGE_REQUEST (
    REQUEST_ID     VARCHAR(36)   NOT NULL,
    PRIVILEGE      VARCHAR(64)   NOT NULL,
    TITLE          VARCHAR(500),
    SUMMARY        VARCHAR(1000),
    RUN_ID         VARCHAR(36),
    METHOD         VARCHAR(8)    NOT NULL,
    PATH           VARCHAR(1000) NOT NULL,
    PAYLOAD        VARIANT,
    REQUESTED_BY   VARCHAR(256)  NOT NULL,
    APPROVER_ROLE  VARCHAR(64)   NOT NULL,
    ALLOW_SELF     BOOLEAN       DEFAULT FALSE,
    STATUS         VARCHAR(16)   NOT NULL,   -- PENDING | APPLIED | FAILED | REJECTED | CANCELLED
    DECIDED_BY     VARCHAR(256),
    DECISION_NOTE  VARCHAR(2000),
    RESULT         VARIANT,
    CREATED_AT     TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    DECIDED_AT     TIMESTAMP_LTZ,
    CONSTRAINT PK_CHANGE_REQUEST PRIMARY KEY (REQUEST_ID)
);
CREATE TABLE IF NOT EXISTS {{database}}.GOVERNANCE.GOVERNANCE_EVENT (
    EVENT_ID    VARCHAR(36)  NOT NULL,
    EVENT_TYPE  VARCHAR(32)  NOT NULL,
    ACTOR       VARCHAR(256) DEFAULT CURRENT_USER(),
    TARGET      VARCHAR(500),
    DETAIL      VARIANT,
    CREATED_AT  TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_GOVERNANCE_EVENT PRIMARY KEY (EVENT_ID)
);

GRANT USAGE ON SCHEMA {{database}}.GOVERNANCE TO DATABASE ROLE {{database}}.VIEWER;
GRANT USAGE ON SCHEMA {{database}}.GOVERNANCE TO DATABASE ROLE {{database}}.DATA_ENGINEER;
GRANT USAGE ON SCHEMA {{database}}.GOVERNANCE TO DATABASE ROLE {{database}}.REVIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA {{database}}.GOVERNANCE TO DATABASE ROLE {{database}}.VIEWER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {{database}}.GOVERNANCE TO DATABASE ROLE {{database}}.DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA {{database}}.GOVERNANCE TO DATABASE ROLE {{database}}.REVIEWER;
