-- Knowledge hub: every item gets a lineage (one id across its versions), where it came from (origin and the run that
-- taught it), how sure the writer was, a change note, who verified it and when it should be reviewed again.
-- Items an automatic writer learns can wait for review: STATUS = 'PROPOSED' with IS_CURRENT = FALSE, so the version in
-- use stays current until a steward approves. A replaced version becomes STATUS = 'SUPERSEDED'.

ALTER TABLE {{database}}.KNOWLEDGE.DOMAIN_KNOWLEDGE ADD COLUMN IF NOT EXISTS LINEAGE_ID VARCHAR(64);
ALTER TABLE {{database}}.KNOWLEDGE.DOMAIN_KNOWLEDGE ADD COLUMN IF NOT EXISTS ORIGIN VARCHAR(24);       -- SEED | PACK_IMPORT | USER | COPILOT | MAPPING | STTM | SODA | PROFILING | MODELING | QA | QUALITY | DBT | DOMAIN_AI
ALTER TABLE {{database}}.KNOWLEDGE.DOMAIN_KNOWLEDGE ADD COLUMN IF NOT EXISTS SOURCE_RUN_ID VARCHAR(36);
ALTER TABLE {{database}}.KNOWLEDGE.DOMAIN_KNOWLEDGE ADD COLUMN IF NOT EXISTS CONFIDENCE FLOAT;
ALTER TABLE {{database}}.KNOWLEDGE.DOMAIN_KNOWLEDGE ADD COLUMN IF NOT EXISTS CHANGE_NOTE VARCHAR(2000);
ALTER TABLE {{database}}.KNOWLEDGE.DOMAIN_KNOWLEDGE ADD COLUMN IF NOT EXISTS VERIFIED_BY VARCHAR(256);
ALTER TABLE {{database}}.KNOWLEDGE.DOMAIN_KNOWLEDGE ADD COLUMN IF NOT EXISTS VERIFIED_AT TIMESTAMP_LTZ;
ALTER TABLE {{database}}.KNOWLEDGE.DOMAIN_KNOWLEDGE ADD COLUMN IF NOT EXISTS REVIEW_DUE DATE;
ALTER TABLE {{database}}.KNOWLEDGE.DOMAIN_KNOWLEDGE ADD COLUMN IF NOT EXISTS REVIEWED_BY VARCHAR(256);
ALTER TABLE {{database}}.KNOWLEDGE.DOMAIN_KNOWLEDGE ADD COLUMN IF NOT EXISTS REVIEW_NOTE VARCHAR(2000);

-- one lineage per domain + reference (the key every writer already versions on); items without a reference stand alone
UPDATE {{database}}.KNOWLEDGE.DOMAIN_KNOWLEDGE
   SET LINEAGE_ID = CASE
         WHEN SOURCE_REFERENCE IS NULL THEN KNOWLEDGE_ID
         -- references that already carry a run or test id are versioned on the reference alone (services/knowledge/writer.py)
         WHEN SOURCE_REFERENCE LIKE 'dbt.branch.%' OR SOURCE_REFERENCE LIKE 'soda.brief.%' OR SOURCE_REFERENCE LIKE 'sttm.csv.%'
              OR SOURCE_REFERENCE LIKE 'qa.test.%' OR SOURCE_REFERENCE LIKE 'quality.%' THEN MD5('|' || SOURCE_REFERENCE)
         ELSE MD5(COALESCE(DOMAIN_ID, '') || '|' || SOURCE_REFERENCE) END
 WHERE LINEAGE_ID IS NULL;

UPDATE {{database}}.KNOWLEDGE.DOMAIN_KNOWLEDGE
   SET ORIGIN = CASE
         WHEN CREATED_BY = 'SEED' THEN 'SEED'
         WHEN ARRAY_CONTAINS('UI'::VARIANT, COALESCE(TAGS, [])) THEN 'USER'
         WHEN KNOWLEDGE_TYPE = 'MAPPING_PATTERN' THEN 'MAPPING'
         WHEN KNOWLEDGE_TYPE = 'COLUMN_RULE' THEN 'PROFILING'
         WHEN KNOWLEDGE_TYPE = 'SODA_PATTERN' OR SOURCE_REFERENCE LIKE 'soda.%' THEN 'SODA'
         WHEN SOURCE_REFERENCE LIKE 'transform.%' OR SOURCE_REFERENCE LIKE 'sttm.%' THEN 'STTM'
         WHEN SOURCE_REFERENCE LIKE 'dbt.%' THEN 'DBT'
         WHEN SOURCE_REFERENCE LIKE 'model.%' THEN 'MODELING'
         WHEN KNOWLEDGE_TYPE = 'QA_TEST' THEN 'QA'
         WHEN SOURCE_REFERENCE LIKE 'quality.%' THEN 'QUALITY'
         WHEN ARRAY_CONTAINS('DOMAIN_REVIEW'::VARIANT, COALESCE(TAGS, [])) THEN 'DOMAIN_AI'
         ELSE 'USER' END
 WHERE ORIGIN IS NULL;

UPDATE {{database}}.KNOWLEDGE.DOMAIN_KNOWLEDGE
   SET SOURCE_RUN_ID = CONTENT_JSON:run_id::STRING
 WHERE SOURCE_RUN_ID IS NULL AND CONTENT_JSON:run_id::STRING IS NOT NULL;

-- older versions that a writer flipped to RETIRED while replacing them are superseded, not retired
UPDATE {{database}}.KNOWLEDGE.DOMAIN_KNOWLEDGE K
   SET STATUS = 'SUPERSEDED'
 WHERE NOT K.IS_CURRENT AND K.STATUS IN ('RETIRED', 'ACTIVE')
   AND EXISTS (SELECT 1 FROM {{database}}.KNOWLEDGE.DOMAIN_KNOWLEDGE N
                WHERE N.LINEAGE_ID = K.LINEAGE_ID AND N.VERSION > K.VERSION);

CREATE TABLE IF NOT EXISTS {{database}}.KNOWLEDGE.KNOWLEDGE_USAGE (
    KNOWLEDGE_ID  VARCHAR(36)   NOT NULL,
    LINEAGE_ID    VARCHAR(64),
    RUN_ID        VARCHAR(36),
    STAGE         VARCHAR(32)   NOT NULL,
    USED_BY       VARCHAR(256)  DEFAULT CURRENT_USER(),
    USED_AT       TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

GRANT SELECT, INSERT, UPDATE ON TABLE {{database}}.KNOWLEDGE.DOMAIN_KNOWLEDGE TO DATABASE ROLE {{database}}.DATA_ENGINEER;
GRANT SELECT, INSERT ON TABLE {{database}}.KNOWLEDGE.KNOWLEDGE_USAGE TO DATABASE ROLE {{database}}.DATA_ENGINEER;
GRANT SELECT ON TABLE {{database}}.KNOWLEDGE.KNOWLEDGE_USAGE TO DATABASE ROLE {{database}}.VIEWER;
