-- Code context: client repositories cloned with Snowflake's Git integration, split into dbt-aware chunks with
-- lineage edges, searchable through CODE.CODE_SEARCH and quoted into stage prompts. Credentials stay in Snowflake
-- secrets referenced by name; the index never stores credential files.
CREATE SCHEMA IF NOT EXISTS {{database}}.CODE COMMENT = 'Indexed client code repositories for prompt context';

CREATE TABLE IF NOT EXISTS {{database}}.CODE.REPO (
    REPO_ID          VARCHAR(36)   NOT NULL,
    NAME             VARCHAR(128)  NOT NULL,
    GIT_URL          VARCHAR(1024) NOT NULL,
    PROVIDER         VARCHAR(32),          -- GITHUB | GITLAB | BITBUCKET | AZURE_DEVOPS | OTHER
    BRANCH           VARCHAR(256)  DEFAULT 'main',
    GIT_REPOSITORY   VARCHAR(512)  NOT NULL, -- the Snowflake GIT REPOSITORY object
    API_INTEGRATION  VARCHAR(256),
    SECRET_NAME      VARCHAR(512),
    DOMAIN_IDS       ARRAY,                -- empty: serves every domain
    INCLUDE_GLOBS    ARRAY,
    EXCLUDE_GLOBS    ARRAY,
    KIND             VARCHAR(16)   DEFAULT 'MIXED', -- DBT | SQL | PYTHON | MIXED
    ENABLED          BOOLEAN       DEFAULT TRUE,
    SCHEDULE_CRON    VARCHAR(128),
    LAST_COMMIT      VARCHAR(64),
    LAST_INDEXED_AT  TIMESTAMP_LTZ,
    STATUS           VARCHAR(16)   DEFAULT 'NEW', -- NEW | INDEXING | READY | FAILED
    ERROR            VARCHAR(4000),
    STATS            VARIANT,              -- files, chunks, edges, dbt projects, languages
    CREATED_BY       VARCHAR(256)  DEFAULT CURRENT_USER(),
    CREATED_AT       TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CODE_REPO PRIMARY KEY (REPO_ID)
);

CREATE TABLE IF NOT EXISTS {{database}}.CODE.CODE_FILE (
    REPO_ID     VARCHAR(36)   NOT NULL,
    PATH        VARCHAR(2048) NOT NULL,
    LANG        VARCHAR(16),
    FILE_HASH   VARCHAR(64),   -- the stage's md5, so a refresh re-reads only changed files
    SIZE        NUMBER(12,0),
    COMMIT_SHA  VARCHAR(64),
    INDEXED_AT  TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CODE_FILE PRIMARY KEY (REPO_ID, PATH)
);

CREATE TABLE IF NOT EXISTS {{database}}.CODE.CODE_CHUNK (
    CHUNK_ID    VARCHAR(64)   NOT NULL,
    REPO_ID     VARCHAR(36)   NOT NULL,
    PATH        VARCHAR(2048) NOT NULL,
    START_LINE  NUMBER(8,0),
    END_LINE    NUMBER(8,0),
    KIND        VARCHAR(24),   -- DBT_MODEL | DBT_SNAPSHOT | DBT_MACRO | DBT_TEST | DBT_SCHEMA_YML | DBT_SOURCE | SQL | PY_FUNC | DOC | CONFIG
    NAME        VARCHAR(512),
    TEXT        VARCHAR(16777216),
    TOKENS      NUMBER(8,0),
    REFS        ARRAY,
    SOURCES     ARRAY,
    COLUMNS     ARRAY,
    TESTS       ARRAY,
    PROJECT     VARCHAR(256),
    COMMIT_SHA  VARCHAR(64),
    CONSTRAINT PK_CODE_CHUNK PRIMARY KEY (CHUNK_ID)
) CHANGE_TRACKING = TRUE;

CREATE TABLE IF NOT EXISTS {{database}}.CODE.CODE_EDGE (
    REPO_ID        VARCHAR(36)  NOT NULL,
    FROM_CHUNK_ID  VARCHAR(64),
    FROM_NAME      VARCHAR(512) NOT NULL,
    TO_NAME        VARCHAR(512) NOT NULL,
    KIND           VARCHAR(16)  NOT NULL, -- REF | SOURCE | MACRO_USE | CALLS | IMPORTS
    PATH           VARCHAR(2048),
    ORIGIN         VARCHAR(16)  DEFAULT 'PARSER', -- PARSER | GRAPH
    COMMIT_SHA     VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS {{database}}.CODE.REPO_SUMMARY (
    REPO_ID     VARCHAR(36)   NOT NULL,
    KIND        VARCHAR(32)   NOT NULL, -- DBT | ARCHITECTURE
    SUMMARY     VARIANT,
    COMMIT_SHA  VARCHAR(64),
    UPDATED_AT  TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_REPO_SUMMARY PRIMARY KEY (REPO_ID, KIND)
);

CREATE TABLE IF NOT EXISTS {{database}}.CODE.INDEX_RUN (
    INDEX_RUN_ID   VARCHAR(36)   NOT NULL,
    REPO_ID        VARCHAR(36)   NOT NULL,
    STARTED_AT     TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    FINISHED_AT    TIMESTAMP_LTZ,
    STATUS         VARCHAR(16),   -- RUNNING | SUCCEEDED | FAILED
    COMMIT_SHA     VARCHAR(64),
    FILES_SEEN     NUMBER(10,0),
    FILES_CHANGED  NUMBER(10,0),
    FILES_REMOVED  NUMBER(10,0),
    CHUNKS         NUMBER(10,0),
    EDGES          NUMBER(10,0),
    DURATION_MS    NUMBER(12,0),
    TRIGGERED_BY   VARCHAR(256)  DEFAULT CURRENT_USER(),
    ERROR          VARCHAR(4000),
    CONSTRAINT PK_INDEX_RUN PRIMARY KEY (INDEX_RUN_ID)
);

CREATE TABLE IF NOT EXISTS {{database}}.CODE.CODE_USAGE (
    CHUNK_ID  VARCHAR(64)   NOT NULL,
    REPO_ID   VARCHAR(36),
    RUN_ID    VARCHAR(36),
    STAGE     VARCHAR(32)   NOT NULL,
    USED_BY   VARCHAR(256)  DEFAULT CURRENT_USER(),
    USED_AT   TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

GRANT USAGE ON SCHEMA {{database}}.CODE TO DATABASE ROLE {{database}}.VIEWER;
GRANT USAGE ON SCHEMA {{database}}.CODE TO DATABASE ROLE {{database}}.DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA {{database}}.CODE TO DATABASE ROLE {{database}}.VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA {{database}}.CODE TO DATABASE ROLE {{database}}.VIEWER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {{database}}.CODE TO DATABASE ROLE {{database}}.DATA_ENGINEER;
