-- Jira Cloud for QA: per-user OAuth tokens (refresh tokens encrypted with a key held by the API host), sign-in state,
-- links between issues and runs or QA tests, and a log of every write made to Jira.
CREATE SCHEMA IF NOT EXISTS {{database}}.JIRA COMMENT = 'Jira Cloud connection for QA';

CREATE TABLE IF NOT EXISTS {{database}}.JIRA.USER_TOKEN (
    USER_NAME      VARCHAR(256)  NOT NULL,
    CLOUD_ID       VARCHAR(64)   NOT NULL,
    SITE_URL       VARCHAR(512),
    ACCOUNT_ID     VARCHAR(128),
    DISPLAY_NAME   VARCHAR(256),
    REFRESH_TOKEN  BINARY,        -- ENCRYPT(refresh token, key from the API host); rotated on every refresh
    SCOPES         ARRAY,
    CONNECTED_AT   TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT     TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_JIRA_USER_TOKEN PRIMARY KEY (USER_NAME, CLOUD_ID)
);

CREATE TABLE IF NOT EXISTS {{database}}.JIRA.OAUTH_STATE (
    STATE       VARCHAR(64)   NOT NULL,   -- one-time value tying Atlassian's callback to the user who started it
    USER_NAME   VARCHAR(256)  NOT NULL,
    RETURN_TO   VARCHAR(512),
    CREATED_AT  TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_JIRA_OAUTH_STATE PRIMARY KEY (STATE)
);

CREATE TABLE IF NOT EXISTS {{database}}.JIRA.ISSUE_LINK (
    LINK_ID       VARCHAR(36)   NOT NULL,
    ISSUE_KEY     VARCHAR(64)   NOT NULL,
    CLOUD_ID      VARCHAR(64)   NOT NULL,
    RUN_ID        VARCHAR(36)   NOT NULL,
    QA_TEST_ID    VARCHAR(64),
    TARGET_TABLE  VARCHAR(512),
    SUMMARY       VARCHAR(1000),
    STATUS        VARCHAR(128),
    IS_DELETED    BOOLEAN       DEFAULT FALSE,
    LINKED_BY     VARCHAR(256)  DEFAULT CURRENT_USER(),
    LINKED_AT     TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_JIRA_ISSUE_LINK PRIMARY KEY (LINK_ID)
);

CREATE TABLE IF NOT EXISTS {{database}}.JIRA.ACTION_LOG (
    ACTION_ID   VARCHAR(36)   NOT NULL,
    ISSUE_KEY   VARCHAR(64)   NOT NULL,
    CLOUD_ID    VARCHAR(64),
    RUN_ID      VARCHAR(36),
    ACTION      VARCHAR(32)   NOT NULL,   -- COMMENT | TRANSITION | LINK | UNLINK | TRIAGE | CONNECT | DISCONNECT
    DETAIL      VARIANT,
    STATUS      VARCHAR(16)   NOT NULL,   -- DONE | FAILED
    ERROR       VARCHAR(2000),
    ACTED_BY    VARCHAR(256)  DEFAULT CURRENT_USER(),
    ACTED_AT    TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_JIRA_ACTION_LOG PRIMARY KEY (ACTION_ID)
);

GRANT USAGE ON SCHEMA {{database}}.JIRA TO DATABASE ROLE {{database}}.VIEWER;
GRANT USAGE ON SCHEMA {{database}}.JIRA TO DATABASE ROLE {{database}}.DATA_ENGINEER;
GRANT USAGE ON SCHEMA {{database}}.JIRA TO DATABASE ROLE {{database}}.REVIEWER;
-- links and the action log are readable by everyone who can see runs; tokens and sign-in state are not
GRANT SELECT ON TABLE {{database}}.JIRA.ISSUE_LINK TO DATABASE ROLE {{database}}.VIEWER;
GRANT SELECT ON TABLE {{database}}.JIRA.ACTION_LOG TO DATABASE ROLE {{database}}.VIEWER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {{database}}.JIRA TO DATABASE ROLE {{database}}.DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {{database}}.JIRA TO DATABASE ROLE {{database}}.REVIEWER;
