-- QA workspace: tests that target a domain's target table with or without a run, grouped in suites per table; Jira
-- links to tables and suites; a shared, versioned Jira access token with a refresh lease so API replicas do not race
-- on Atlassian's rotating refresh tokens; and a QA_ENGINEER database role that can write tests without sign-off.
-- Every statement is safe to run again (IF NOT EXISTS, DROP NOT NULL on an already nullable column is a no-op).

-- tests: a run's tests keep RUN_ID; table tests have RUN_ID NULL and SCOPE = 'TABLE'
ALTER TABLE {{database}}.CONTRACT.QA_TEST_CASE ALTER COLUMN RUN_ID DROP NOT NULL;
ALTER TABLE {{database}}.CONTRACT.QA_TEST_CASE ADD COLUMN IF NOT EXISTS DOMAIN_ID VARCHAR(36);
ALTER TABLE {{database}}.CONTRACT.QA_TEST_CASE ADD COLUMN IF NOT EXISTS TARGET_TABLE_ID VARCHAR(36);
ALTER TABLE {{database}}.CONTRACT.QA_TEST_CASE ADD COLUMN IF NOT EXISTS SUITE_ID VARCHAR(36);
ALTER TABLE {{database}}.CONTRACT.QA_TEST_CASE ADD COLUMN IF NOT EXISTS SCOPE VARCHAR(8) DEFAULT 'RUN';   -- RUN | TABLE
ALTER TABLE {{database}}.CONTRACT.QA_TEST_CASE ADD COLUMN IF NOT EXISTS TARGET_FQN VARCHAR(1024);

-- suites of table tests (CONTRACT.QA_SUITE is already a procedure, so the table has another name)
CREATE TABLE IF NOT EXISTS {{database}}.CONTRACT.QA_TEST_SUITE (
    SUITE_ID         VARCHAR(36)   NOT NULL,
    DOMAIN_ID        VARCHAR(36),
    TARGET_TABLE_ID  VARCHAR(36)   NOT NULL,
    NAME             VARCHAR(200)  NOT NULL,
    DESCRIPTION      VARCHAR(2000),
    IS_DEFAULT       BOOLEAN       DEFAULT FALSE,   -- the suite a run's QA lane also executes for its target
    IS_DELETED       BOOLEAN       DEFAULT FALSE,
    CREATED_BY       VARCHAR(256),
    CREATED_AT       TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT       TIMESTAMP_LTZ,
    CONSTRAINT PK_QA_TEST_SUITE PRIMARY KEY (SUITE_ID)
);

-- QA runs and results: standalone runs store RUN_ID NULL and never touch a run's sign-off gate
ALTER TABLE {{database}}.QUALITY.QA_RUN ALTER COLUMN RUN_ID DROP NOT NULL;
ALTER TABLE {{database}}.QUALITY.QA_RUN ADD COLUMN IF NOT EXISTS DOMAIN_ID VARCHAR(36);
ALTER TABLE {{database}}.QUALITY.QA_RUN ADD COLUMN IF NOT EXISTS TARGET_TABLE_ID VARCHAR(36);
ALTER TABLE {{database}}.QUALITY.QA_RUN ADD COLUMN IF NOT EXISTS SUITE_ID VARCHAR(36);
ALTER TABLE {{database}}.QUALITY.QA_RUN ADD COLUMN IF NOT EXISTS SCOPE VARCHAR(8) DEFAULT 'RUN';         -- RUN | TABLE
ALTER TABLE {{database}}.QUALITY.QA_RUN ADD COLUMN IF NOT EXISTS TRIGGER_DETAIL VARIANT;                 -- e.g. the Jira issue that triggered a retest

ALTER TABLE {{database}}.QUALITY.QA_RESULT ALTER COLUMN RUN_ID DROP NOT NULL;
ALTER TABLE {{database}}.QUALITY.QA_RESULT ADD COLUMN IF NOT EXISTS TARGET_TABLE_ID VARCHAR(36);
ALTER TABLE {{database}}.QUALITY.QA_RESULT ADD COLUMN IF NOT EXISTS SUITE_ID VARCHAR(36);

-- Jira links to a table, a suite or a test, with the issue's last known state for the inbox and auto-retest
ALTER TABLE {{database}}.JIRA.ISSUE_LINK ALTER COLUMN RUN_ID DROP NOT NULL;
ALTER TABLE {{database}}.JIRA.ISSUE_LINK ADD COLUMN IF NOT EXISTS DOMAIN_ID VARCHAR(36);
ALTER TABLE {{database}}.JIRA.ISSUE_LINK ADD COLUMN IF NOT EXISTS TARGET_TABLE_ID VARCHAR(36);
ALTER TABLE {{database}}.JIRA.ISSUE_LINK ADD COLUMN IF NOT EXISTS SUITE_ID VARCHAR(36);
ALTER TABLE {{database}}.JIRA.ISSUE_LINK ADD COLUMN IF NOT EXISTS ISSUE_ID VARCHAR(40);                 -- stable across key changes (project moves)
ALTER TABLE {{database}}.JIRA.ISSUE_LINK ADD COLUMN IF NOT EXISTS STATUS_CATEGORY VARCHAR(40);
ALTER TABLE {{database}}.JIRA.ISSUE_LINK ADD COLUMN IF NOT EXISTS ISSUE_STATE VARCHAR(12) DEFAULT 'OK';   -- OK | MOVED | DELETED | HIDDEN
ALTER TABLE {{database}}.JIRA.ISSUE_LINK ADD COLUMN IF NOT EXISTS ORIGIN VARCHAR(8) DEFAULT 'LINK';      -- LINK | BUG
ALTER TABLE {{database}}.JIRA.ISSUE_LINK ADD COLUMN IF NOT EXISTS SOURCE_RESULT_ID VARCHAR(36);         -- the failing QA result a bug was raised from
ALTER TABLE {{database}}.JIRA.ISSUE_LINK ADD COLUMN IF NOT EXISTS LAST_SYNCED_AT TIMESTAMP_LTZ;
ALTER TABLE {{database}}.JIRA.ISSUE_LINK ADD COLUMN IF NOT EXISTS LAST_SEEN_STATUS VARCHAR(100);
ALTER TABLE {{database}}.JIRA.ISSUE_LINK ADD COLUMN IF NOT EXISTS LAST_RETEST_AT TIMESTAMP_LTZ;

-- shared access token and a refresh lease: one replica refreshes (compare-and-swap on TOKEN_VERSION), the rest wait
ALTER TABLE {{database}}.JIRA.USER_TOKEN ADD COLUMN IF NOT EXISTS ACCESS_TOKEN BINARY;                  -- ENCRYPT(access token, key from the API host)
ALTER TABLE {{database}}.JIRA.USER_TOKEN ADD COLUMN IF NOT EXISTS ACCESS_EXPIRES_AT TIMESTAMP_LTZ;
ALTER TABLE {{database}}.JIRA.USER_TOKEN ADD COLUMN IF NOT EXISTS TOKEN_VERSION NUMBER DEFAULT 0;
ALTER TABLE {{database}}.JIRA.USER_TOKEN ADD COLUMN IF NOT EXISTS LEASE_BY VARCHAR(80);
ALTER TABLE {{database}}.JIRA.USER_TOKEN ADD COLUMN IF NOT EXISTS LEASE_UNTIL TIMESTAMP_LTZ;

ALTER TABLE {{database}}.JIRA.ACTION_LOG ADD COLUMN IF NOT EXISTS ACTOR_KIND VARCHAR(8) DEFAULT 'USER';  -- USER | BOT | SYSTEM
ALTER TABLE {{database}}.JIRA.ACTION_LOG ADD COLUMN IF NOT EXISTS IDEMPOTENCY_KEY VARCHAR(64);

-- QA_ENGINEER: writes and runs QA tests and works Jira issues; no write on CONTRACT.QA_SIGNOFF (sign-off is unchanged).
-- Grant it to the account role QA people use: GRANT DATABASE ROLE {{database}}.QA_ENGINEER TO ROLE <account_role>
CREATE DATABASE ROLE IF NOT EXISTS {{database}}.QA_ENGINEER COMMENT = 'Write and run QA tests, work Jira issues';
GRANT DATABASE ROLE {{database}}.VIEWER      TO DATABASE ROLE {{database}}.QA_ENGINEER;
GRANT DATABASE ROLE {{database}}.QA_ENGINEER TO DATABASE ROLE {{database}}.DATA_ENGINEER;

GRANT USAGE ON SCHEMA {{database}}.CONTRACT TO DATABASE ROLE {{database}}.QA_ENGINEER;
GRANT USAGE ON SCHEMA {{database}}.QUALITY  TO DATABASE ROLE {{database}}.QA_ENGINEER;
GRANT USAGE ON SCHEMA {{database}}.JIRA     TO DATABASE ROLE {{database}}.QA_ENGINEER;
GRANT SELECT, INSERT, UPDATE ON TABLE {{database}}.CONTRACT.QA_TEST_CASE  TO DATABASE ROLE {{database}}.QA_ENGINEER;
GRANT SELECT, INSERT, UPDATE ON TABLE {{database}}.CONTRACT.QA_TEST_SUITE TO DATABASE ROLE {{database}}.QA_ENGINEER;
GRANT SELECT, INSERT ON TABLE {{database}}.QUALITY.QA_RUN    TO DATABASE ROLE {{database}}.QA_ENGINEER;
GRANT SELECT, INSERT ON TABLE {{database}}.QUALITY.QA_RESULT TO DATABASE ROLE {{database}}.QA_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {{database}}.JIRA TO DATABASE ROLE {{database}}.QA_ENGINEER;

GRANT SELECT ON TABLE {{database}}.CONTRACT.QA_TEST_SUITE TO DATABASE ROLE {{database}}.VIEWER;
GRANT SELECT ON TABLE {{database}}.CONTRACT.QA_TEST_SUITE TO DATABASE ROLE {{database}}.REVIEWER;
