"""Publish generated dbt code to GitHub: cut a branch, commit the files on top of the base tree, open a PR.

Snowflake git repository clones are read-only from SQL (COPY FILES can't target them), so writes go through
the GitHub REST API. The commit uses the base branch tree, so every skeleton file stays exactly as it is
on the cut-from branch and only the generated paths are added or replaced.

`Request` is injected: Snowflake's CODEGEN.PUBLISH_DBT_PR passes an urllib caller that runs through an
external access integration with a token from a Snowflake SECRET; tests pass a fake.
"""

from __future__ import annotations

import json
import re
from typing import Any, Callable, Dict, List, Optional, Tuple
from urllib.parse import quote

Request = Callable[[str, str, Optional[Dict[str, Any]]], Tuple[int, Any]]

ORIGIN = re.compile(r"^(?:https?://(?:[^@/]+@)?github\.com/|git@github\.com:)([A-Za-z0-9_.-]+)/([A-Za-z0-9_.-]+?)(?:\.git)?/?$")
BRANCH = re.compile(r"^(?!/)(?!.*\.\.)(?!.*//)[A-Za-z0-9._/-]{1,200}(?<!/)(?<!\.lock)$")
SKIP_PATHS = ("release/workspace.json",)


class PublishError(RuntimeError):
    def __init__(self, step: str, status: int, detail: Any):
        message = detail.get("message") if isinstance(detail, dict) else str(detail)
        super().__init__(f"{step} failed ({status}): {message}")
        self.step, self.status = step, status


def parse_origin(origin: str) -> Tuple[str, str]:
    match = ORIGIN.match((origin or "").strip())
    if not match:
        raise ValueError(f"not a GitHub repository URL: {origin}")
    return match.group(1), match.group(2)


def check_branch(name: str) -> str:
    value = (name or "").strip()
    if not BRANCH.match(value):
        raise ValueError(f"invalid branch name: {name}")
    return value


def tree_entries(files: Dict[str, str]) -> List[Dict[str, str]]:
    out = []
    for path, content in sorted(files.items()):
        clean = path.replace("\\", "/").lstrip("/")
        if not clean or ".." in clean.split("/") or clean in SKIP_PATHS:
            continue
        out.append({"path": clean, "mode": "100644", "type": "blob", "content": content})
    return out


def pr_body(run_name: str, run_id: str, files: List[str], sttm_id: Optional[str], notes: str = "") -> str:
    models = [f for f in files if f.startswith("models/") and f.endswith(".sql")]
    lines = [
        f"Generated by the Agentic pipeline for run **{run_name or run_id}** (`{run_id}`).",
        "",
        f"- Approved STTM: `{sttm_id}`" if sttm_id else "- Built from the approved STTM",
        f"- {len(files)} files ({len(models)} models); every other file on the base branch is unchanged",
        "- Compile-only in Snowflake (`DEFAULT_WRITEBACK = FALSE`) until this PR is reviewed and merged",
        "",
        "### Models",
        *[f"- `{m}`" for m in models[:40]],
    ]
    if notes:
        lines += ["", notes]
    return "\n".join(lines)


def _ok(step: str, result: Tuple[int, Any], *allowed: int) -> Any:
    status, body = result
    if status not in (allowed or (200, 201)):
        raise PublishError(step, status, body)
    return body


def publish(request: Request, origin: str, base: str, head: str, files: Dict[str, str],
            title: str, body: str, message: str, draft: bool = False) -> Dict[str, Any]:
    owner, repo = parse_origin(origin)
    base, head = check_branch(base), check_branch(head)
    if base == head:
        raise ValueError("the new branch must differ from the cut-from branch")
    entries = tree_entries(files)
    if not entries:
        raise ValueError("no files to publish")
    root = f"/repos/{owner}/{repo}"

    base_ref = _ok("read base branch", request("GET", f"{root}/git/ref/heads/{quote(base, safe='/')}", None))
    base_sha = base_ref["object"]["sha"]
    status, head_ref = request("GET", f"{root}/git/ref/heads/{quote(head, safe='/')}", None)
    branch_existed = status == 200
    if status not in (200, 404):
        raise PublishError("read head branch", status, head_ref)
    parent = head_ref["object"]["sha"] if branch_existed else base_sha
    parent_commit = _ok("read parent commit", request("GET", f"{root}/git/commits/{parent}", None))

    tree = _ok("create tree", request("POST", f"{root}/git/trees",
                                      {"base_tree": parent_commit["tree"]["sha"], "tree": entries}))
    if tree["sha"] == parent_commit["tree"]["sha"]:
        commit_sha, changed = parent, False
    else:
        commit = _ok("create commit", request("POST", f"{root}/git/commits",
                                              {"message": message, "tree": tree["sha"], "parents": [parent]}))
        commit_sha, changed = commit["sha"], True
        if branch_existed:
            _ok("update branch", request("PATCH", f"{root}/git/refs/heads/{quote(head, safe='/')}",
                                         {"sha": commit_sha, "force": False}))
    if not branch_existed:
        _ok("create branch", request("POST", f"{root}/git/refs", {"ref": f"refs/heads/{head}", "sha": commit_sha}))

    open_prs = _ok("find pull request", request(
        "GET", f"{root}/pulls?state=open&head={quote(owner)}:{quote(head, safe='')}&base={quote(base, safe='')}", None))
    if open_prs:
        pr, pr_created = open_prs[0], False
    elif commit_sha == base_sha:
        pr, pr_created = {}, False  # nothing differs from the base branch, GitHub would reject the PR
    else:
        pr = _ok("open pull request", request("POST", f"{root}/pulls",
                                              {"title": title, "head": head, "base": base, "body": body, "draft": draft}))
        pr_created = True
    return {
        "status": "PUBLISHED" if pr else "NO_CHANGES",
        "provider": "GITHUB",
        "repository": f"{owner}/{repo}",
        "base_branch": base,
        "head_branch": head,
        "branch_created": not branch_existed,
        "commit_sha": commit_sha,
        "changed": changed,
        "files_pushed": len(entries),
        "pull_request": {"number": pr.get("number"), "url": pr.get("html_url"), "created": pr_created,
                         "state": pr.get("state"), "draft": pr.get("draft")},
    }


def urllib_request(token: str, api: str = "https://api.github.com", timeout: int = 30) -> Request:
    """GitHub REST caller using only the standard library (works inside Snowflake Python procedures)."""
    import urllib.error
    import urllib.request

    def call(method: str, path: str, payload: Optional[Dict[str, Any]]) -> Tuple[int, Any]:
        data = json.dumps(payload).encode("utf-8") if payload is not None else None
        req = urllib.request.Request(f"{api}{path}", data=data, method=method, headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": "gdp-agent-platform",
            **({"Content-Type": "application/json"} if data is not None else {}),
        })
        try:
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                raw = resp.read().decode("utf-8")
                return resp.status, json.loads(raw) if raw else {}
        except urllib.error.HTTPError as exc:
            raw = exc.read().decode("utf-8", "replace")
            try:
                return exc.code, json.loads(raw)
            except ValueError:
                return exc.code, {"message": raw[:300]}

    return call
