-- Watermark registration for a newly onboarded source.
-- Replace <SOURCE_SYSTEM_NAME>, <SOURCE_KEY_UPPER>, <ENTITY_UPPER>.
INSERT INTO DEV_GDP_UTIL_DB.CONFIG.GDP_DBT_WATERMARK_TBL
  (SOURCE_SYSTEM, SOURCE_MODEL_NAME, TARGET_MODEL_NAME, WATERMARK_TIMESTAMP, GDP_INSERTED_TS, GDP_UPDATED_TS)
SELECT
  '<SOURCE_SYSTEM_NAME>',
  '<SOURCE_KEY_UPPER>_<ENTITY_UPPER>',
  '<ENTITY_UPPER>',
  '1900-01-01'::TIMESTAMP_NTZ,
  CURRENT_TIMESTAMP::TIMESTAMP_NTZ(6),
  CURRENT_TIMESTAMP::TIMESTAMP_NTZ(6)
WHERE NOT EXISTS (
    SELECT 1 FROM DEV_GDP_UTIL_DB.CONFIG.GDP_DBT_WATERMARK_TBL
    WHERE SOURCE_SYSTEM = '<SOURCE_SYSTEM_NAME>'
      AND SOURCE_MODEL_NAME = '<SOURCE_KEY_UPPER>_<ENTITY_UPPER>'
      AND TARGET_MODEL_NAME = '<ENTITY_UPPER>'
);
