-- Reporting views. Re-applied on every deploy.

CREATE OR REPLACE VIEW {{database}}.AUDIT.V_RUN_COST AS
SELECT RUN_ID, STAGE, MODEL,
       SUM(INPUT_TOKENS)       AS INPUT_TOKENS,
       SUM(OUTPUT_TOKENS)      AS OUTPUT_TOKENS,
       SUM(TOTAL_TOKENS)       AS TOTAL_TOKENS,
       SUM(TOOL_CALL_COUNT)    AS TOOL_CALLS,
       SUM(SEARCH_CALL_COUNT)  AS SEARCH_CALLS,
       SUM(CODE_CALL_COUNT)    AS CODE_CALLS,
       SUM(DURATION_MS)        AS DURATION_MS,
       SUM(ESTIMATED_COST)     AS ESTIMATED_CREDITS
  FROM {{database}}.AUDIT.COST_USAGE
 GROUP BY RUN_ID, STAGE, MODEL;

-- Mapping feedback: how the top-ranked candidate compared with the reviewer's current decision.
CREATE OR REPLACE VIEW {{database}}.MAPPING.V_MAPPING_FEEDBACK AS
SELECT C.RUN_ID,
       C.SOURCE_COLUMN_ID,
       C.TARGET_COLUMN_ID      AS PROPOSED_TARGET_COLUMN_ID,
       C.FINAL_SCORE,
       C.RECOMMENDATION,
       D.DECISION,
       D.TARGET_COLUMN_ID      AS DECIDED_TARGET_COLUMN_ID,
       IFF(D.DECISION = 'APPROVED' AND D.TARGET_COLUMN_ID = C.TARGET_COLUMN_ID, TRUE, FALSE) AS ACCEPTED,
       IFF(D.DECISION IN ('MODIFIED', 'ALTERNATIVE_TARGET'), TRUE, FALSE)                    AS OVERRIDDEN,
       IFF(D.DECISION = 'REJECTED', TRUE, FALSE)                                            AS REJECTED,
       D.REVIEWER,
       D.REVIEWED_AT
  FROM {{database}}.MAPPING.MAPPING_CANDIDATE C
  LEFT JOIN {{database}}.MAPPING.MAPPING_DECISION D
    ON D.RUN_ID = C.RUN_ID AND D.SOURCE_COLUMN_ID = C.SOURCE_COLUMN_ID AND D.IS_CURRENT
 WHERE C.IS_CURRENT AND C.RANK = 1;

GRANT SELECT ON VIEW {{database}}.AUDIT.V_RUN_COST TO DATABASE ROLE {{database}}.VIEWER;
GRANT SELECT ON VIEW {{database}}.MAPPING.V_MAPPING_FEEDBACK TO DATABASE ROLE {{database}}.VIEWER;
