-- ============================================================================
-- Schema Clone Runbook
-- Source : {SOURCE_DB}.{SOURCE_SCHEMA}
-- Target : {TARGET_DB}.{TARGET_SCHEMA}
-- Layer  : {GOLD|SILVER}
-- Env    : {DEV|QA|UAT|PROD}
-- Prefix : {PREFIX}  (project audit-column / shared-object namespace; may be blank)
-- Generated by skill: schema-ddl-extraction
-- ============================================================================

USE ROLE {ROLE};
USE WAREHOUSE {WAREHOUSE};

-- ----------------------------------------------------------------------------
-- 1. Target schema
-- ----------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS {TARGET_DB}.{TARGET_SCHEMA};

-- ----------------------------------------------------------------------------
-- 2. Sequences
-- ----------------------------------------------------------------------------
-- ===== SEQUENCE: SEQ_{TABLE}_SKEY =====
CREATE OR REPLACE SEQUENCE {TARGET_DB}.{TARGET_SCHEMA}.SEQ_{TABLE}_SKEY
  START 1 INCREMENT 1
  COMMENT = 'Surrogate key sequence for {TABLE}';

-- ----------------------------------------------------------------------------
-- 3. Tables
-- ----------------------------------------------------------------------------
-- ============================================================================
-- TABLE: {TABLE}
-- ============================================================================
CREATE OR REPLACE ICEBERG TABLE {TARGET_DB}.{TARGET_SCHEMA}.{TABLE} (
    {TABLE}_SKEY                   LONG NOT NULL  COMMENT 'Surrogate primary key',
    DIM_{PREFIX}_DATA_SOURCE_SKEY   NUMBER(3,0)    COMMENT 'FK to source system reference',  -- INJECTED BY schema-ddl-extraction (NUMBER(3,0) to match parent PK type)
    -- ... business columns ...
    {PREFIX}_IS_ACTIVE              BOOLEAN NOT NULL  COMMENT 'Active flag',
    {PREFIX}_INSERTED_TS            TIMESTAMP_NTZ NOT NULL  COMMENT 'Inserted timestamp',
    {PREFIX}_INSERTED_BY            STRING NOT NULL  COMMENT 'Inserted by',
    {PREFIX}_UPDATED_TS             TIMESTAMP_NTZ NOT NULL  COMMENT 'Updated timestamp',
    {PREFIX}_UPDATED_BY             STRING NOT NULL  COMMENT 'Updated by',
    CONSTRAINT PK_{TABLE} PRIMARY KEY ({TABLE}_SKEY),
    CONSTRAINT FK_{TABLE}_DIM_{PREFIX}_DATA_SOURCE_SKEY
      FOREIGN KEY (DIM_{PREFIX}_DATA_SOURCE_SKEY)
      REFERENCES {ENV}_{PREFIX}_SILVER_DB.SHARED.REF_{PREFIX}_SOURCE_SYSTEM({PREFIX}_SOURCE_SYSTEM_SKEY)
)
EXTERNAL_VOLUME = '{EXTERNAL_VOLUME}'
CATALOG         = 'SNOWFLAKE'
BASE_LOCATION   = '{BASE_LOCATION}'
COMMENT = '{TABLE_COMMENT}';

-- ----------------------------------------------------------------------------
-- 4. Views
-- ----------------------------------------------------------------------------
-- ===== VIEW: {VIEW} =====
CREATE OR REPLACE VIEW {TARGET_DB}.{TARGET_SCHEMA}.{VIEW} AS
SELECT ...
;

-- ----------------------------------------------------------------------------
-- 5. Materialized Views / Dynamic Tables
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- 6. Streams
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- 7. File Formats / Stages
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- 8. Functions
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- 9. Procedures
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- 10. Tasks  (resume LAST, after all dependencies are in place)
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- 11. Grants  (optional)
-- ----------------------------------------------------------------------------
